trigger:
  batch: true
  branches:
    include:
      - dev

pool:
  vmImage: "ubuntu-latest"

extends:
  template: ./templates/bicep.template.yaml
  parameters:
    environmentName: "dev"
    locationCode: "auea"
